### ISSUE TITLE
JOSS: Does authorship match contributions?

### ISSUE THREAD

**Issue by kellykochanski** [EcoJulia/EcologicalNetworks.jl#166]
The JOSS paper is listed with three authors; however, the github contribution insights show commits from only one of them (tpoisot). 

Can you please elaborate on the contributions made to the software by each author? Documentation showing that the contributing author wrote a significant part of the software would be ideal.

As a reminder, JOSS is open to different authorship conventions based on field, but does require that the contributing author has made a "substantial contribution" to the software, and that authors have made more than financial contributions.

**Comment by tpoisot** [comment]
Thank you for pointing this out - @francisbanville is starting a *Ph.D.* on ecological networks, and his project implies that he will take over most of the development of `EcologicalNetworks.jl`. Writing this article as a way to initiate this process.

It must also be noted that @francisbanville has been *very* active in outreach on the package, and notably gave a talk at the latest JuliaCon meeting, which formed the basis for the content of the article. This is not a "code" contribution, but I think that this is a very important one for the adoption of the tool.

**Comment by FrancisBanville** [comment]
Thanks @tpoisot. 

I also want to specify that @SteveViss has been the main contributor to @mangal-wg. His contribution to Mangal was substantial, and this is why he is an author of this article.

**Comment by SteveViss** [comment]
Thanks @FrancisBanville for flagging me out in this issue. @kellykochanski, I redesigned the mangal v2 backend (database + REST API) which feeds the client `mangal.jl` and allows the `EcologicalNetworks.jl` to exist. Let me know if you need further details on my contribution.

**Comment by KristinaRiemer** [comment]
All of these authorship contributions are sufficient according to JOSS standards, thanks to everyone for clarifying their roles!

**Comment by kellykochanski** [comment]
This looks good. Thank you for clarifying!
