### ISSUE TITLE
JOSS: Slight clarification of installation instructions

### ISSUE THREAD

**Issue by kellykochanski** [EcoJulia/EcologicalNetworks.jl#167]
## What to do?

- Add command line instruction for entering package mode in Julia
- If feasible (not required), update requirements to say whether package works with more recent versions of Julia than 1.0

## Why?

To remove ambiguity from language + instructions.

**Comment by FrancisBanville** [comment]
Thanks for your comment @kellykochanski!

Command line instructions for entering package mode in Julia have been added to the `Mangal.jl` and `EcologicalNetworks.jl` repositories. I also specified in the manuscript which versions of Julia are supported.
