### ISSUE TITLE
JOSS: EcoJulia link doesn't work.

### ISSUE THREAD

**Issue by arbennett** [EcoJulia/EcologicalNetworks.jl#170]
In the JOSS paper text there is a link to EcoJulia given as https://ecojulia.github.io/ - however, I am getting "Site not found".

**Comment by tpoisot** [comment]
Good catch - the new URL is `https://ecojulia.org/` -- @FrancisBanville this is a trivial fix.

**Comment by FrancisBanville** [comment]
@arbennett Thank you for catching that! I just fixed it.
