### ISSUE TITLE
JOSS: Include code example in docs

### ISSUE THREAD

**Issue by arbennett** [EcoJulia/EcologicalNetworks.jl#171]
One of the review criteria for the JOSS paper in the documentation section is:
> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)

Currently the docs don't have a concrete example that would help new users get up and running. The code examples given in the paper itself, however, are really nice and could be an easy inclusion into the docs. I think that it would be really helpful to have this example in the docs, or even just a link to the script in the paper directory.

**Comment by tpoisot** [comment]
@FrancisBanville I think it can be a good idea to have a "Use-cases" section like in the Mangal doc, with some examples that are specific to this package. Thanks @arbennett for flagging this!

**Comment by FrancisBanville** [comment]
Thank you for your suggestion @arbennett!  We added [an example](https://ecojulia.github.io/EcologicalNetworks.jl/dev/examples/integration_mangal/) inspired from the code example given in the paper, and will definitely add more examples in the upcoming months.

**Comment by arbennett** [comment]
Excellent! I just read through the example and think it's great! Closing.
