### ISSUE TITLE
Modularity for bipartite networks

### ISSUE THREAD

**Issue by Inazuma110** [EcoJulia/EcologicalNetworks.jl#187]
**Is your feature request related to a problem? Please describe.**
EcologicalNetworks.jl has a function to compute the modularity of networks.
However, it has been shown in several papers that a different definition of modularity for bipartite graphs can be used for more accurate community detection.

**Describe the solution you'd like**
This is Barber’s modularity definition.
![image](https://user-images.githubusercontent.com/31335755/109378677-df26c200-7917-11eb-8444-b493d8cbea5a.png)
I think we can define this equation as follows:
```jl
Q(N::T, L::Dict{E,Int64}) where {T<:AbstractBipartiteNetwork,E}
```

**Describe alternatives you've considered**

**Additional context**
Reference:
- [Modularity and community detection in bipartite networks](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.76.066102#fulltext)
- [A method for detecting modules in quantitative bipartite networks](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12139)
- [Improved community detection in weighted bipartite networks](https://royalsocietypublishing.org/doi/full/10.1098/rsos.140536)

**Comment by tpoisot** [comment]
Hi @Inazuma110 - this is indeed what [Q](https://github.com/EcoJulia/EcologicalNetworks.jl/blob/main/src/modularity/utilities.jl#L14) does -- I'm marking this issue as closed, the definition we have in the code works for binary and probabilistic networks.
