### ISSUE TITLE
Base.contains and Base.in overload for determining if a species is in a network

### ISSUE THREAD

**Issue by gottacatchenall** [EcoJulia/EcologicalNetworks.jl#196]
Maybe I'm missing an easy way that exists already to do this but an interface for checking if a given taxon is in a network 
would be useful by overloading a couple base functions, e.g.

```
Base.contains(network::NT, taxon::String) where {NT <: AbstractEcologicalNetwork} = taxon in network 

Base.in(taxon::String, net::NT) where {NT <: UnipartiteNetwork } = taxon in net.S
Base.in(taxon::String, net::NT) where {NT <: UnipartiteNetwork } = taxon in net.T || taxon in net.B
```

will add in #194 if it sounds good

**Comment by tpoisot** [comment]
I don't super like it, because we have `taxon in species(N)` already... Also, I think in `a in b` , `a` should be of the `eltype` of `b`.

**Comment by gottacatchenall** [comment]
wrote this prior to discovering the `species` methods :clown_face: 

agreed that makes sense
